package com.company.Homework13;

public enum  ProductName {

    LAYS, PRINGLES, DORITOS, CHEETOS, OTMARTINA,
    SNICKERS, MARS, RAFFAELLO, BOUNTY, KINDER,
    NOYAN, FANTA, COCACOLA, SPRITE, SANDORA,
    NOY, BYUREGH, JERMUK, APARAN, EVIAN,
    KILIKIA, GYUMRI, STELLA, BALTIKA, DARGETT,
    MARLBORO, PARLIAMENT, ARARAT, AKHTAMAR, CAMEL
}
